/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TickerRouteImport } from './routes/$ticker'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAssistRouteImport } from './routes/api/assist'

const TickerRoute = TickerRouteImport.update({
  id: '/$ticker',
  path: '/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistRoute = ApiAssistRouteImport.update({
  id: '/api/assist',
  path: '/api/assist',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$ticker': typeof TickerRoute
  '/api/assist': typeof ApiAssistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$ticker': typeof TickerRoute
  '/api/assist': typeof ApiAssistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$ticker': typeof TickerRoute
  '/api/assist': typeof ApiAssistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$ticker' | '/api/assist'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$ticker' | '/api/assist'
  id: '__root__' | '/' | '/$ticker' | '/api/assist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TickerRoute: typeof TickerRoute
  ApiAssistRoute: typeof ApiAssistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$ticker': {
      id: '/$ticker'
      path: '/$ticker'
      fullPath: '/$ticker'
      preLoaderRoute: typeof TickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assist': {
      id: '/api/assist'
      path: '/api/assist'
      fullPath: '/api/assist'
      preLoaderRoute: typeof ApiAssistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TickerRoute: TickerRoute,
  ApiAssistRoute: ApiAssistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
